### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by radien** [ingles98/Bitburner-Scripts#2]
Copied all the files and got this error..

/map/netmap.js@home

Failed to resolve module specifier "DOM_utils.js". Relative references must start with either "/", "./", or "../".
stack:
TypeError: Failed to resolve module specifier "DOM_utils.js". Relative references must start with either "/", "./", or "../".

DOM_utils.js is a blank file

**Comment by ingles98** [comment]
the original DOM_utils.js is in [the root dir of the repo ](https://github.com/ingles98/Bitburner-Scripts/blob/master/DOM_utils.js).
